### ISSUE TITLE
How to actually run the website locally ?

### ISSUE THREAD

**Issue by GoldEEr17** [Tenpi/Cuteanime.moe#1]
Your website seems to be great, as if i understand what it can do then we can basically import any video+subs files and watch it in a webbrowser so that we can use yomichan, plus some interface related to the anime etc. But since it's currently no longer up because of the cost, which i undertand, i don't actually know how it looks like and i've never seen anybody talk about it.

The problem I have is that you provide some steps to run it locally, but since they are very vague and unclear I doubt anybody with a bit of experience with it could actually make it work. Or at least, it seems very unclear to me as to what exactly should be done to get the website launched, how to import the anime we want etc.

That is a shame because your work seems very interesting to use, but it's not currently useable... 
Could you (or anyone that could be reading this) actually make a more detailed explanation of the process of running it ? It doesn't appear to be that long based on the few lines supposedly explaining it, but a step-by-step small guide or even filming screen while doing it could definitely help a lot. Looking forward to use your website.

**Comment by Tenpi** [comment]
I didn't think it was that difficult to understand but I will try to give you really detailed instructions. 

If you look in `database.js` you will find the anticipated file structure for local running.
<img width="657" alt="Screenshot 2023-05-31 at 12 32 19 PM" src="https://github.com/Tenpi/Cuteanime.moe/assets/37512637/e50d1198-c336-4940-ba58-ba076740e766">
```
Anime
├── Anime Name 1
│   ├── English (VTT subtitles)
│   ├── Japanese (VTT subtitles)
│   ├── Thumbnails (JPG thumbnails)
│   ├── Videos (MP4 videos)
│   └── cover.jpg
├── Anime Name 2
│   ├── English (VTT subtitles)
│   ├── Japanese (VTT subtitles)
│   ├── Thumbnails (JPG thumbnails)
│   ├── Videos (MP4 videos)
│   └── cover.jpg
└── etc.
```
Create a folder named "Anime" somewhere and add several folders named "Anime Name" containing the subtitles, videos, thumbnails (optional), and cover image (optional).
<img width="756" alt="Screenshot 2023-05-31 at 12 48 25 PM" src="https://github.com/Tenpi/Cuteanime.moe/assets/37512637/340400e8-3ddc-4453-b064-52e3de135001">

The name of the files should be "Anime Title (episode number)"
<img width="748" alt="Screenshot 2023-05-31 at 12 48 50 PM" src="https://github.com/Tenpi/Cuteanime.moe/assets/37512637/765a43ba-f896-468b-a89a-cd691f4d4280">

The subtitles should be in WebVTT format. I have another app that provides a SRT/ASS to VTT converter and a bulk renamer that renames files like "folder title (number)". https://github.com/Tenpi/Image-Compressor 

Then `database.js` should be filled in like the following (you can get most info from wikipedia).
<img width="633" alt="Screenshot 2023-05-31 at 12 54 57 PM" src="https://github.com/Tenpi/Cuteanime.moe/assets/37512637/8dc7bb4c-0821-4926-8429-92aaef710f0f">

(Optional) you can add a synopsis per episode also by filling in `episodes.js`.
<img width="548" alt="Screenshot 2023-05-31 at 12 56 30 PM" src="https://github.com/Tenpi/Cuteanime.moe/assets/37512637/76ba93cb-e007-4f01-a40e-cd836a79ef0f">

Here, replace `/Volumes/Files` with the location where you placed your "Anime" folder. https://github.com/Tenpi/Cuteanime.moe/blob/1b12ab3803c1ca5e767c32ac05f43f72ef0217fb/server.tsx#LL47C8-L47C8 

If you did everything correctly, now you should be able to run the website and watch the anime that you added.
`npm install` (Only need to run this once) \
`npm start` \
Website should be at `http://localhost:8081` by default.

You are in charge of making sure the subtitles are synced properly. A useful tool to use is this, but it won't always be accurate. https://github.com/kaegi/alass 
There is also this online tool that will shift all the subs by a certain amount of ms. https://subtitletools.com/subtitle-sync-shifter

**Comment by GoldEEr17** [comment]
Thank you for that amazing answer, now when I run npm start in the console after going to the correct folder with the cd command, and even though npm install seemed to have worked properly, I have an issue with "Failed to load ./.env"...
I've looked it up a bit about what .env is supposed to be but it didn't really help me as to what I should be doing to make it work here... How is it supposed to be for you ? That might be a common thing but I don't know much about it

**Comment by Tenpi** [comment]
This `.env` file is not important, but to remove the message you can create a `.env` file in the project root and fill it with `TESTING=no`. (If you set `TESTING=yes`, it will run the website in development mode).
